# Generated by Django 5.2.5 on 2025-08-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_remove_mailing_is_active_alter_mailing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Завершение рассылки"
            ),
        ),
    ]
