# Generated by Django 5.2.5 on 2025-08-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_started_at_alter_mailing_finished_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["pk"],
                "permissions": [("can_finished_mailing", "Can finished mailing")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
