# Generated by Django 5.2.5 on 2025-08-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["topik"],
                "permissions": [("can_view_message", "Can view message")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "permissions": [("can_view_recipient", "Can view recipient")],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
    ]
