# Generated by Django 5.2.5 on 2025-08-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_message_options_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["pk"],
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_finished_mailing", "Can finished mailing"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
